version: "3.8"

services:
  web:
    image: nginx:alpine
    container_name: navigation-app
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      app-network:
        ipv4_address: 172.20.0.100  # Assign a static IP address
  jupyter:
    image: quay.io/jupyter/base-notebook:82d322f00937
    container_name: jupyter_lab_PMR
    user: root
    volumes:
      - ./app:/home/jovyan/work
    ports:
      - "8899:8888"
    command: >
      start-notebook.sh
      --NotebookApp.token=''
      --NotebookApp.password=''
      --NotebookApp.allow_root=True
    networks:
      app-network:
        ipv4_address: 172.20.0.101  # Assign a static IP address
   
networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24  # Define the subnet for the network
